
import React, { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import { 
  Send, 
  Bot, 
  User, 
  Code, 
  Loader2,
  CheckCircle,
  Github,
  Clock,
  Wifi,
  WifiOff,
  Zap
} from 'lucide-react';
import { useRealTimeAIGeneration } from '@/hooks/useRealTimeAIGeneration';
import { useRealTimeGitHub } from '@/hooks/useRealTimeGitHub';
import { useRealTimeChatHistory } from '@/hooks/useRealTimeChatHistory';
import { useRealTimeDeployment } from '@/hooks/useRealTimeDeployment';

interface RealTimeSimplifiedChatbotProps {
  projectId: string;
  sourceCode: string;
  channelData?: any;
  onCodeUpdate: (newCode: string, targetFile?: string) => void;
  onChatHistoryUpdate: (history: any[]) => void;
}

const RealTimeSimplifiedChatbot: React.FC<RealTimeSimplifiedChatbotProps> = ({
  projectId,
  sourceCode,
  channelData,
  onCodeUpdate,
  onChatHistoryUpdate
}) => {
  const [input, setInput] = useState('');
  const [connectionStatus, setConnectionStatus] = useState<'connected' | 'disconnected' | 'connecting'>('connected');
  const [verificationStatus, setVerificationStatus] = useState<'none' | 'in-progress' | 'approved' | 'rejected'>('none');
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Real-time hooks
  const { generateWithAI, loading: aiLoading } = useRealTimeAIGeneration();
  const { uploadToGitHub, uploading: githubUploading } = useRealTimeGitHub();
  const { deployToNetlify, deploymentStatus } = useRealTimeDeployment();
  const { messages, addMessage } = useRealTimeChatHistory(projectId);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
    onChatHistoryUpdate(messages);
  }, [messages, onChatHistoryUpdate]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || aiLoading) return;

    const userInput = input;
    setInput('');
    setConnectionStatus('connecting');

    try {
      // Add user message immediately
      await addMessage({
        type: 'user',
        content: userInput
      });

      // Generate AI response in real-time
      const aiResponse = await generateWithAI(
        userInput,
        projectId,
        channelData
      );

      if (aiResponse && aiResponse.generatedCode) {
        // Update code preview immediately
        onCodeUpdate(aiResponse.generatedCode);

        let githubUrl: string | null = null;
        let netlifyUrl: string | null = null;

        // Upload to GitHub in real-time
        if (aiResponse.generatedCode) {
          console.log('🚀 Starting real-time GitHub upload...');
          
          const projectName = channelData?.title 
            ? `${channelData.title}-website`
            : `ai-website-${Date.now()}`;

          const files = [
            {
              path: 'index.html',
              content: aiResponse.generatedCode,
              message: `🎯 Real-time update: ${userInput.substring(0, 50)}...`
            },
            {
              path: 'README.md',
              content: `# ${projectName}\n\nAI-generated website with real-time updates.\n\n## Features\n- Modern responsive design\n- Real-time AI generation\n- YouTube integration\n- Professional animations\n\n## Last Updated\n${new Date().toISOString()}\n\n## Generated by\nAI Website Builder with real-time capabilities`
            }
          ];

          githubUrl = await uploadToGitHub(projectId, projectName, files);
        }

        // Deploy to Netlify in real-time
        if (aiResponse.generatedCode) {
          console.log('🌐 Starting real-time deployment...');
          const projectName = channelData?.title 
            ? `${channelData.title}-website`
            : `ai-website-${Date.now()}`;
          
          netlifyUrl = await deployToNetlify(
            projectId,
            projectName,
            aiResponse.generatedCode
          );
        }

        // Add bot response with GitHub and Netlify links
        await addMessage({
          type: 'bot',
          content: aiResponse.reply,
          feature: aiResponse.feature,
          generatedCode: aiResponse.generatedCode,
          codeDescription: aiResponse.codeDescription,
          githubUrl: githubUrl || undefined,
          netlifyUrl: netlifyUrl || undefined
        });

        // Set verification as in progress
        setVerificationStatus('in-progress');
      } else if (aiResponse) {
        // Add bot response without code
        await addMessage({
          type: 'bot',
          content: aiResponse.reply,
          feature: aiResponse.feature
        });
      }

      setConnectionStatus('connected');
    } catch (error) {
      console.error('❌ Error in chat submission:', error);
      setConnectionStatus('disconnected');
      
      await addMessage({
        type: 'bot',
        content: `❌ **Error Processing Request**\n\nSorry, I encountered an error: ${error instanceof Error ? error.message : 'Unknown error'}\n\n🔄 Please try again with a more specific request.`
      });
    }
  };

  const getConnectionIcon = () => {
    switch (connectionStatus) {
      case 'connected':
        return <Wifi className="w-4 h-4 text-green-500" />;
      case 'connecting':
        return <Loader2 className="w-4 h-4 text-yellow-500 animate-spin" />;
      case 'disconnected':
        return <WifiOff className="w-4 h-4 text-red-500" />;
    }
  };

  const getStatusBadge = () => {
    if (aiLoading || githubUploading) {
      return <Badge variant="secondary" className="bg-blue-100 text-blue-700">
        <Loader2 className="w-3 h-3 mr-1 animate-spin" />
        Generating
      </Badge>;
    }
    
    if (deploymentStatus.status === 'deploying') {
      return <Badge variant="secondary" className="bg-purple-100 text-purple-700">
        <Loader2 className="w-3 h-3 mr-1 animate-spin" />
        Deploying
      </Badge>;
    }
    
    if (deploymentStatus.status === 'deployed') {
      return <Badge variant="secondary" className="bg-green-100 text-green-700">
        <CheckCircle className="w-3 h-3 mr-1" />
        Live
      </Badge>;
    }
    
    if (verificationStatus === 'in-progress') {
      return <Badge variant="secondary" className="bg-orange-100 text-orange-700">
        <Clock className="w-3 h-3 mr-1" />
        Verification in Progress
      </Badge>;
    }
    
    return null;
  };

  return (
    <div className="h-full flex flex-col bg-white/90 backdrop-blur-sm">
      {/* Header */}
      <div className="p-4 border-b border-red-200/50 bg-red-50/80">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-red-600 rounded-full flex items-center justify-center">
              <Bot className="w-4 h-4 text-white" />
            </div>
            <div>
              <h3 className="font-semibold text-gray-800">Real-Time AI Assistant</h3>
              <div className="flex items-center gap-2">
                {getConnectionIcon()}
                <span className="text-xs text-gray-600 capitalize">{connectionStatus}</span>
                <Zap className="w-3 h-3 text-yellow-500" title="Real-time enabled" />
              </div>
            </div>
          </div>
          {getStatusBadge()}
        </div>
      </div>

      {/* Messages */}
      <ScrollArea className="flex-1 p-4">
        <div className="space-y-4">
          {messages.map((message) => (
            <div
              key={message.id}
              className={`flex gap-3 ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}
            >
              {message.type === 'bot' && (
                <div className="w-8 h-8 bg-red-600 rounded-full flex items-center justify-center flex-shrink-0">
                  <Bot className="w-4 h-4 text-white" />
                </div>
              )}
              
              <div className={`max-w-[80%] ${message.type === 'user' ? 'order-1' : ''}`}>
                <div
                  className={`rounded-lg p-3 ${
                    message.type === 'user'
                      ? 'bg-red-600 text-white ml-auto'
                      : 'bg-gray-100 text-gray-800'
                  }`}
                >
                  <div className="whitespace-pre-wrap text-sm">{message.content}</div>
                  
                  {message.generatedCode && (
                    <div className="mt-2 p-2 bg-black/10 rounded border-l-2 border-green-500">
                      <div className="flex items-center gap-1 text-xs font-medium mb-1">
                        <Code className="w-3 h-3" />
                        <Zap className="w-3 h-3" />
                        Real-Time Code Generated
                      </div>
                      <div className="text-xs opacity-80">
                        {message.codeDescription}
                      </div>
                    </div>
                  )}
                  
                  {message.githubUrl && (
                    <div className="mt-2">
                      <a 
                        href={message.githubUrl} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-xs bg-black/10 hover:bg-black/20 px-2 py-1 rounded transition-colors"
                      >
                        <Github className="w-3 h-3" />
                        <Zap className="w-3 h-3" />
                        Real-Time GitHub Upload
                      </a>
                    </div>
                  )}
                  
                  {message.netlifyUrl && (
                    <div className="mt-2">
                      <a 
                        href={message.netlifyUrl} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-xs bg-blue-500 hover:bg-blue-600 text-white px-2 py-1 rounded transition-colors"
                      >
                        <CheckCircle className="w-3 h-3" />
                        <Zap className="w-3 h-3" />
                        Live Deployment
                      </a>
                    </div>
                  )}
                </div>
                
                <div className="text-xs text-gray-500 mt-1 px-1">
                  {message.timestamp.toLocaleTimeString([], { 
                    hour: '2-digit', 
                    minute: '2-digit' 
                  })}
                </div>
              </div>

              {message.type === 'user' && (
                <div className="w-8 h-8 bg-gray-600 rounded-full flex items-center justify-center flex-shrink-0">
                  <User className="w-4 h-4 text-white" />
                </div>
              )}
            </div>
          ))}
          
          {aiLoading && (
            <div className="flex gap-3 justify-start">
              <div className="w-8 h-8 bg-red-600 rounded-full flex items-center justify-center">
                <Bot className="w-4 h-4 text-white" />
              </div>
              <div className="bg-gray-100 rounded-lg p-3">
                <div className="flex items-center gap-2">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <Zap className="w-4 h-4 text-yellow-500" />
                  <span className="text-sm text-gray-600">Real-time AI generation...</span>
                </div>
              </div>
            </div>
          )}
        </div>
        <div ref={messagesEndRef} />
      </ScrollArea>

      {/* Input */}
      <form onSubmit={handleSubmit} className="p-4 border-t border-red-200/50 bg-red-50/80">
        <div className="flex gap-2">
          <Input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask AI to create your website in real-time..."
            disabled={aiLoading}
            className="flex-1 bg-white/90 border-red-200 focus:border-red-400"
          />
          <Button
            type="submit"
            disabled={aiLoading || !input.trim()}
            className="bg-red-600 hover:bg-red-700 text-white"
          >
            {aiLoading ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Send className="w-4 h-4" />
            )}
          </Button>
        </div>
        
        <div className="mt-2 text-xs text-gray-600 text-center flex items-center justify-center gap-1">
          <Zap className="w-3 h-3 text-yellow-500" />
          Real-time AI • GitHub • Deployment • Chat History
        </div>
      </form>
    </div>
  );
};

export default RealTimeSimplifiedChatbot;
